# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "{pass-your-node-type-id}"

# please note that we're using FUSE reference for config file, hence we're going to load this file using its local FS path
environments:
  default:
    strict_path_adjustment_policy: true
    jobs:
      ##################################################################
      # this is an example job with single ETL task based on 2.0 API  #
      #################################################################
      - name: "semantic-layer-data-preparation"
        <<: *basic-static-cluster
        spark_python_task:
          python_file: "file://semantic_layer_data_preparation/workloads/data_preparation.py"
          parameters: ["--conf-file", "file:fuse://conf/data_preparation.yml"]
