version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/Dockerfile.frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
  backend:
    build:
      context: ./uc-semantic-layer
      dockerfile: ../dockerfiles/Dockerfile.backend
    ports:
      - 8000:8000
    env_file:
      - .env