# pull official base image
FROM node:18.2.0-slim

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install -g npm@8.12.1
RUN npm install --legacy-peer-deps

# add app
COPY . ./

# start app
CMD ["npm", "start"]