FROM python:3.9.12

WORKDIR /server

COPY server-requirements.txt .
RUN pip install -r server-requirements.txt

COPY ./ .
RUN pip install -e .

ENTRYPOINT [ "uvicorn", "uc_semantic_layer.backend.server:app", "--host", "0.0.0.0", "--port", "8000",  "--log-config", "conf/server_log.yml"]



